/*
 * SSD_prog.c
 *
 *  Created on: ??þ/??þ/????
 *      Author: Belal
 */
#include "types.h"
#include "util.h"
#include "SSD_interface.h"
#include "SSD_config.h"
#include "DIO_interface.h"

const u8 SSD_u8ValArr[SSD_u8COMMCOUNT][SSD_u8NUMSCOUNT][SSD_u8SEGCOUNT] = {{
		{ DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW },
		{ DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW },
		{ DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH },
		{ DIO_u8HIGH, DIO_u8HIGH,DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH },
		{ DIO_u8LOW,DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH },
		{ DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH,DIO_u8HIGH },
		{ DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH,DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH },
		{ DIO_u8HIGH, DIO_u8HIGH,DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW },
		{DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH,DIO_u8HIGH, DIO_u8HIGH },
		 { DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH,DIO_u8HIGH, DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH }},
		 {{ DIO_u8LOW,DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW,DIO_u8HIGH },
		 { DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH,DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH },
		 { DIO_u8LOW, DIO_u8LOW,DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH, DIO_u8LOW },
		 {DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH,DIO_u8HIGH, DIO_u8LOW },
		 { DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW,DIO_u8HIGH, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW },
		 { DIO_u8LOW,DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW, DIO_u8HIGH, DIO_u8LOW,DIO_u8LOW },
		 { DIO_u8LOW, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW,DIO_u8LOW, DIO_u8LOW, DIO_u8LOW },
		 { DIO_u8LOW, DIO_u8LOW,DIO_u8LOW, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH, DIO_u8HIGH },
		 {DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW, DIO_u8LOW,DIO_u8LOW, DIO_u8LOW },
		 { DIO_u8LOW, DIO_u8LOW, DIO_u8LOW,DIO_u8LOW, DIO_u8HIGH, DIO_u8LOW, DIO_u8LOW }}};

#if (SSD_u8DISPCOUNT==1)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
		{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG }

		  };
#elif (SSD_u8DISPCOUNT==2)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
		{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG },
		  { SSD_u8DISP2_SEGA,SSD_u8DISP2_SEGB, SSD_u8DISP2_SEGC, SSD_u8DISP2_SEGD, SSD_u8DISP2_SEGE, SSD_u8DISP2_SEGF, SSD_u8DISP2_SEGG }
		  };
#elif (SSD_u8DISPCOUNT==3)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG },
		  { SSD_u8DISP2_SEGA,SSD_u8DISP2_SEGB, SSD_u8DISP2_SEGC, SSD_u8DISP2_SEGD, SSD_u8DISP2_SEGE, SSD_u8DISP2_SEGF, SSD_u8DISP2_SEGG },
		  { SSD_u8DISP3_SEGA,SSD_u8DISP3_SEGB, SSD_u8DISP3_SEGC, SSD_u8DISP3_SEGD, SSD_u8DISP3_SEGE, SSD_u8DISP3_SEGF, SSD_u8DISP3_SEGG }
		  };
#elif (SSD_u8DISPCOUNT==4)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
		{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG },
		  { SSD_u8DISP2_SEGA,SSD_u8DISP2_SEGB, SSD_u8DISP2_SEGC, SSD_u8DISP2_SEGD, SSD_u8DISP2_SEGE, SSD_u8DISP2_SEGF, SSD_u8DISP2_SEGG },
		  { SSD_u8DISP3_SEGA,SSD_u8DISP3_SEGB, SSD_u8DISP3_SEGC, SSD_u8DISP3_SEGD, SSD_u8DISP3_SEGE, SSD_u8DISP3_SEGF, SSD_u8DISP3_SEGG },
		  { SSD_u8DISP4_SEGA,SSD_u8DISP4_SEGB, SSD_u8DISP4_SEGC, SSD_u8DISP4_SEGD, SSD_u8DISP4_SEGE, SSD_u8DISP4_SEGF, SSD_u8DISP4_SEGG }
		};
#elif (SSD_u8DISPCOUNT==5)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
		{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG },
		  { SSD_u8DISP2_SEGA,SSD_u8DISP2_SEGB, SSD_u8DISP2_SEGC, SSD_u8DISP2_SEGD, SSD_u8DISP2_SEGE, SSD_u8DISP2_SEGF, SSD_u8DISP2_SEGG },
		  { SSD_u8DISP3_SEGA,SSD_u8DISP3_SEGB, SSD_u8DISP3_SEGC, SSD_u8DISP3_SEGD, SSD_u8DISP3_SEGE, SSD_u8DISP3_SEGF, SSD_u8DISP3_SEGG },
		  { SSD_u8DISP4_SEGA,SSD_u8DISP4_SEGB, SSD_u8DISP4_SEGC, SSD_u8DISP4_SEGD, SSD_u8DISP4_SEGE, SSD_u8DISP4_SEGF, SSD_u8DISP4_SEGG },
		  { SSD_u8DISP5_SEGA,SSD_u8DISP5_SEGB, SSD_u8DISP5_SEGC, SSD_u8DISP5_SEGD, SSD_u8DISP5_SEGE, SSD_u8DISP5_SEGF, SSD_u8DISP5_SEGG }
		};
#elif (SSD_u8DISPCOUNT==6)
const u8 SSD_u8DispArr[SSD_u8DISPCOUNT][SSD_u8SEGCOUNT] =
		{ { SSD_u8DISP1_SEGA,SSD_u8DISP1_SEGB, SSD_u8DISP1_SEGC, SSD_u8DISP1_SEGD, SSD_u8DISP1_SEGE, SSD_u8DISP1_SEGF, SSD_u8DISP1_SEGG },
		  { SSD_u8DISP2_SEGA,SSD_u8DISP2_SEGB, SSD_u8DISP2_SEGC, SSD_u8DISP2_SEGD, SSD_u8DISP2_SEGE, SSD_u8DISP2_SEGF, SSD_u8DISP2_SEGG },
		  { SSD_u8DISP3_SEGA,SSD_u8DISP3_SEGB, SSD_u8DISP3_SEGC, SSD_u8DISP3_SEGD, SSD_u8DISP3_SEGE, SSD_u8DISP3_SEGF, SSD_u8DISP3_SEGG },
		  { SSD_u8DISP4_SEGA,SSD_u8DISP4_SEGB, SSD_u8DISP4_SEGC, SSD_u8DISP4_SEGD, SSD_u8DISP4_SEGE, SSD_u8DISP4_SEGF, SSD_u8DISP4_SEGG },
		  { SSD_u8DISP5_SEGA,SSD_u8DISP5_SEGB, SSD_u8DISP5_SEGC, SSD_u8DISP5_SEGD, SSD_u8DISP5_SEGE, SSD_u8DISP5_SEGF, SSD_u8DISP5_SEGG },
		  { SSD_u8DISP6_SEGA,SSD_u8DISP6_SEGB, SSD_u8DISP6_SEGC, SSD_u8DISP6_SEGD, SSD_u8DISP6_SEGE, SSD_u8DISP6_SEGF, SSD_u8DISP6_SEGG }
		  };

#endif

const u8 SSD_u8DispCommArr[SSD_u8DISPMAXCOUNT]={SSD_u8DISP1TYPE,SSD_u8DISP2TYPE,SSD_u8DISP3TYPE,SSD_u8DISP4TYPE,SSD_u8DISP5TYPE,SSD_u8DISP6TYPE};

const u8 SSD_u8DispInitValArr[SSD_u8DISPMAXCOUNT]={SSD_u8DISP1_INITVAL,SSD_u8DISP2_INITVAL,SSD_u8DISP3_INITVAL,SSD_u8DISP4_INITVAL,SSD_u8DISP5_INITVAL,SSD_u8DISP6_INITVAL};

const u8 SSD_u8DispCommPin[SSD_u8DISPMAXCOUNT]={SSD_u8DISP1_INITCOM,SSD_u8DISP2_INITCOM,SSD_u8DISP3_INITCOM,SSD_u8DISP4_INITCOM,SSD_u8DISP5_INITCOM,SSD_u8DISP6_INITCOM};

const u8 SSD_u8DispCommStatus[SSD_u8COMMCOUNT][SSD_u8STATUSCOUNT]={{DIO_u8HIGH,DIO_u8LOW},{DIO_u8LOW,DIO_u8HIGH}};

static u8 SSD_u8DispValArr[SSD_u8DISPMAXCOUNT]={SSD_u8DISP1_INITVAL,SSD_u8DISP2_INITVAL,SSD_u8DISP3_INITVAL,SSD_u8DISP4_INITVAL,SSD_u8DISP5_INITVAL,SSD_u8DISP6_INITVAL};

static u8 SSD_u8DispStatusArr[SSD_u8DISPMAXCOUNT]={SSD_u8DISP1_INITSTATE,SSD_u8DISP2_INITSTATE,SSD_u8DISP3_INITSTATE,SSD_u8DISP4_INITSTATE,SSD_u8DISP5_INITSTATE,SSD_u8DISP6_INITSTATE};

extern void SSD_voidInit(void) {

	u8 Local_u8DispCounter ;
	u8 Local_u8SegCounter ;
	DIO_voidInit();
	for (Local_u8DispCounter=0;Local_u8DispCounter< SSD_u8DISPMAXCOUNT;Local_u8DispCounter++){
		/*Comment!: Set ON or OFF status */
		     DIO_u8WritePinVal(SSD_u8DispCommPin[Local_u8DispCounter],
			 SSD_u8DispCommStatus[SSD_u8DispCommArr[Local_u8DispCounter]][SSD_u8DispStatusArr[Local_u8DispCounter]]);
			/*Comment!: Set initial value */
			for (Local_u8SegCounter=0;Local_u8SegCounter < SSD_u8SEGCOUNT;Local_u8SegCounter++){
						   DIO_u8WritePinVal(SSD_u8DispArr[Local_u8DispCounter][Local_u8SegCounter],
						   SSD_u8ValArr[SSD_u8DispCommArr[SSD_u8DispInitValArr[Local_u8DispCounter]]]
						   [SSD_u8DispInitValArr[Local_u8DispCounter]][Local_u8SegCounter]);

					   }
	}
	return ;
}

extern u8 SSD_u8Display(u8 Copy_u8DispIdx, u8 Copy_u8DispVal) {
	u8 Local_u8ReturnFlag = OK;
	u8 Local_u8Counter ;
	if (Copy_u8DispIdx > SSD_u8DISPCOUNT || Copy_u8DispVal > SSD_u8NUMSCOUNT) {
		Local_u8ReturnFlag = ERROR;
	} else {
           for (Local_u8Counter=SSD_u8SEGCOUNT;Local_u8Counter>0;Local_u8Counter--){
        	   DIO_u8WritePinVal(SSD_u8DispArr[Copy_u8DispIdx][SSD_u8SEGCOUNT-Local_u8Counter], SSD_u8ValArr[SSD_u8DispCommArr[Copy_u8DispIdx]][Copy_u8DispVal][SSD_u8SEGCOUNT-Local_u8Counter]);
           }
           if (SSD_u8DispStatusArr[Copy_u8DispIdx]==SSD_u8ONSTATE){
                   SSD_u8DispValArr[Copy_u8DispIdx]=Copy_u8DispVal;
           }
           else {
                // Do nothing
           }
		Local_u8ReturnFlag = OK;
	}

	return Local_u8ReturnFlag;

}

extern u8 SSD_u8GetVal(u8 Copy_u8DispIdx , u8* Copy_u8DispVal){
	u8 Local_u8ReturnFlag = OK;
	if (Copy_u8DispIdx > SSD_u8DISPCOUNT ) {
			Local_u8ReturnFlag = ERROR;
	} else {
			*Copy_u8DispVal =SSD_u8DispValArr[Copy_u8DispIdx];
			Local_u8ReturnFlag = OK;
		    }

   return Local_u8ReturnFlag;
}

extern u8 SSD_u8TurnOn(u8 Copy_u8DispIdx){

	u8 Local_u8ReturnFlag = OK;
		if (Copy_u8DispIdx > SSD_u8DISPCOUNT ) {
			Local_u8ReturnFlag = ERROR;

		}
		else {
			        SSD_u8DispStatusArr[Copy_u8DispIdx]=SSD_u8ONSTATE;
			        DIO_u8WritePinVal(SSD_u8DispCommPin[Copy_u8DispIdx],SSD_u8DispCommStatus[SSD_u8DispCommArr[Copy_u8DispIdx]][SSD_u8DispStatusArr[Copy_u8DispIdx]]);
			        Local_u8ReturnFlag = OK;
				    }
		 return Local_u8ReturnFlag;
}


extern u8 SSD_u8TurnOff(u8 Copy_u8DispIdx){

	u8 Local_u8ReturnFlag = OK;
		if (Copy_u8DispIdx > SSD_u8DISPCOUNT ) {
			Local_u8ReturnFlag = ERROR;

		}
		else {
			        SSD_u8DispStatusArr[Copy_u8DispIdx]=SSD_u8OFFSTATE;
			        DIO_u8WritePinVal(SSD_u8DispCommPin[Copy_u8DispIdx],SSD_u8DispCommStatus[SSD_u8DispCommArr[Copy_u8DispIdx]][SSD_u8DispStatusArr[Copy_u8DispIdx]]);
					Local_u8ReturnFlag = OK;
				    }
		 return Local_u8ReturnFlag;
}



